version: "3.8"

networks:
  cache_network:
    driver: bridge
    name: cache_network

services:
  redis:
    container_name: redis_service
    image: "redis"
    command: redis-server
    networks:
      cache_network:
        aliases:
          - redis
    ports:
      - "5000:6379"
    expose:
      - "5000"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  cache_client:
    container_name: cache_client
    build:
      context: "./CacheApp"
      dockerfile: Dockerfile
    image: cache_client
    networks:
      cache_network:
        aliases:
          - cache_client
    ports:
      - "5001:6379"
    expose:
      - "5001"
    environment:
      APP_NAME: "cache_client"
      APP_HOST: 0.0.0.0
      APP_PORT: 6379
      REDIS_HOST: redis 
      REDIS_PORT: 6379

  cache_client2:
    container_name: cache_client2
    build:
      context: "./CacheApp"
      dockerfile: Dockerfile
    image: cache_client
    networks:
      cache_network:
        aliases:
          - cache_client2
    ports:
      - "5002:6379"
    expose:
      - "5002"
    environment:
      APP_NAME: "cache_client"
      APP_HOST: 0.0.0.0
      APP_PORT: 6379
      REDIS_HOST: redis 
      REDIS_PORT: 6379
    

