version: '3.8'

services:
  
  cache_client:
    container_name: cache_client
    depends_on:
      - kafka-1
      - kafka-2
      - zookeeper-1
      - zookeeper-2
    build:
      context: "./CacheApp"
      dockerfile: Dockerfile
    image: cache_client
    ports:
      - "5001:6379"
    expose:
      - "5001"
    environment:
      APP_NAME: "cache_client"
      APP_HOST: 0.0.0.0
      APP_PORT: 6379
      KAFKA_HOST_1: kafka-1 
      KAFKA_HOST_2: kafka-2
      KAFKA_PORT_1: 29092
      KAFKA_PORT_2: 39092
  # cache_client2:
  #   container_name: cache_client2
  #   build:
  #     context: "./CacheApp"
  #     dockerfile: Dockerfile
  #   image: cache_client
  #   networks:
  #     cache_network:
  #       aliases:
  #         - cache_client2
  #   ports:
  #     - "5002:6379"
  #   expose:
  #     - "5002"
  #   environment:
  #     APP_NAME: "cache_client"
  #     APP_HOST: 0.0.0.0
  #     APP_PORT: 6379
  #     REDIS_HOST: redis 
  #     REDIS_PORT: 6379

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181
  
  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TOPICS: "topic:1:1"

  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  